language: node_js
node_js:
- '6'
- '7'
- '8'
- stable
sudo: false
deploy:
  provider: npm
  email: avernacc+gravatar@gmail.com
  api_key:
    secure: NzOXERlL/BgM5/KoIPqiCMbIElUrda++xFWVL4aphdyzroclQJUCMc3FbTc8lXeIvsS7S5CY0zvE+UHSFmwzPZKvR02Ius5xVj5isJb63d2NwH9ACNrM103Wyig2QwsPr0egcTQmkZqlKVdZKKs87kJbKb3sQ0wEdCyCyM3x7CXPOZsCFuq5jQ2R59oCwwLhyW+y6PfYrGZWIBDJB/1MDQCYz2ZSAONRGBhjczt3Fvyf+KnN9zcYXa4+sWF/HRfdmsVcJMHwstpXBf9x/aN0eVWPij/xtZM7Msm4kVchC7AWUqn1Y6bWfABAk6z0P1WClMsz3ZnspP3mFn/+uGAFCRWI4TayF6Q4elIHgrEYGpoVNCmw//Wj594NKLa10fVCcP8bSsCDJb+ay0WDcEjIzxNezcjQrJBwhTx/LOXWYLRnJ2iw7POq5rjMS0oSvuiQm90uMqCazzVhLRA0/QNp0+6mrgjCXagOou0jKSRvTiqVRdMVt04XaR85PM2Fxi7fRR7n8B83dHJ/+Ah7+BCur+BbAdBK4326aFugO87kYx3skNlizVhOIIrehPM2dV89qe9+ykpsG8empl0QAZPkdf3PdExD402C7jM+cN71KbCsap5cHCkg3A1dDxZ2FBLN+c3N0tv/hvaFlT9nCDyXvOR08T8yERXbbv0DWo7VHiY=
  on:
    tags: true
    branch: master
